### ISSUE TITLE
Validation does not work properly with fragments

### ISSUE THREAD

**Issue by jarekCC** [l0rdn1kk0n/wicket-bootstrap#676]
I tried to use SimpleMessageValidation on Fragment which is not yet added to Panel. 

code:
```
Fragment notAddedFragment = ....
Fragment defaultFragment = ....
notAddedFragment.add(form);

final SimpleMessageValidation validation = new SimpleMessageValidation();
validation.getConfig().appendToParent(true);

notAddedFragment.add(validation);
add(defaultFragment);
```
and somewhere else in the code ```addOrReplace(notAddedFragment);```

Unfortunately it is not working. No validation is visible using this approach.

I did a workaround:
```
Fragment notAddedFragment = ....
Fragment defaultFragment = .... 
notAddedFragment.add(form);

final SimpleMessageValidation validation = new SimpleMessageValidation();
validation.getConfig().appendToParent(true);

add(notAddedFragment);
notAddedFragment.add(validation);
addOrReplace(defaultFragment);

```
but I guess validation should work fine in the first approach. Could you fix that?

**Comment by martin-g** [comment]
> Unfortunately it is not working

Unfortunately this doesn't tell us anything. What is the problem exactly ?
Providing a test case or demo application will help us help you!

**Comment by jarekCC** [comment]
Ok I'll try to describe it step by step.

1. I created two wicket Fragments but didn't add it to panel. Let's call them defaultFragment (fragment added at the start) and notAddedFragment(fragment replacing defaultFragment on clickButton).
2. I created a Form and added it to notAddedFragment.
3. I created SimpleMessageValidation and added it to notAddedFragment
4. I added defaultFragment to Panel.
5. I replaced defaultFragment to notAddedFragment with clickButton.
6. Validation is not working (eg. there is no "has-error" class on empty required field after adding form to target)

I thought that it can be a problem with adding Behavior to Fragment that is not yet added to Panel, but I created new behavior with renderHead adding some js, added it to notAddedFragment instead of SimpleMessageValidation and it worked. 

My workaround also worked. The difference is that I added notAddedFragment first, then added validation to it and only then replaced it with defaultFragment. 

It looks like SimpleMessageValidation is simply not working when you first add it to MakupContainer and then add MarkupContainer to eg. Panel instead of first adding MarkupContainer and then SimpleMessageValidation

**Comment by martin-g** [comment]
Since `notAddedFragment` is not yet added to any parent `SimpleMessageValidation` is not in use during `onSubmit()` so it is normal that `it doesn't work`.
If you still believe there is a bug then please create a demo app and I'll reopen this issue!
Thank you!

**Comment by jarekCC** [comment]
it *is* added to parent in runtime, *before* onSubmit is called. It is difference between

```
fragment.add(validation)
add(fragment)
```

and 

```
add(fragment)
fragment.add(validation)
```
In the second case everything works fine. In the first case validation.js is called properly but $container.find('[wb-validation-message]') doesn't find any 'wb-validation-message's.

**Comment by martin-g** [comment]
With these short code snippets it is impossible to understand what could be the problem.

**Comment by eximius313** [comment]
@martin-g I have exactly the same problem
Here is the showcase (that you already know :D )
[wicket-showcase-SimpleMessageValidation.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/1057879/wicket-showcase-SimpleMessageValidation.zip)

To reproduce:
1)Run ./gradlew bootRun
2)Go to http://localhost:8080
3)Hit edit
4)Hit save (validation will fire)
5)Swap lines 62 and 63 in ReadOnlyEditPanel.java
6)Restart ./gradlew bootRun
7)Go to http://localhost:8080
8)Hit edit
9)Hit save (validation will NOT fire)

**Comment by eximius313** [comment]
@martin-g could you please reopen?

**Comment by martin-g** [comment]
I'll take a look soon!
Thank you for the quickstart!

**Comment by martin-g** [comment]
You should use Wicket Bootstrap 2.x when using Wicket 8.x

**Comment by martin-g** [comment]
I am not Gradle user.
How I can tell Gradle to use my local Maven -SNAPSHOTs ? It seems it doesn't use ~/.m2/repository/

**Comment by eximius313** [comment]
I think this should help: https://stackoverflow.com/questions/24454076/how-to-force-gradle-to-use-share-m2-repository-with-maven-system-wide

**Comment by martin-g** [comment]
Gradle is such a pain!
Now IDEA doesn't recognize that the project uses Lombok. With Maven this "Just Works" without any manual work.
Why this project needs to be so complex to show me some problem with a simple Wicket component ...

**Comment by martin-g** [comment]
On command line it starts but fails with:
````
org.apache.wicket.WicketRuntimeException: Property 'page.title' not found in property files. Markup: [markup = file:/home/martin/tmp/wb/676/wicket-showcase/build/resources/main/com/showcase/gui/core/BasePage.html
<wicket:message key="page.title"/>, index = 1, current =  '<wicket:message key="page.title"/>' (line 0, column 0)]
        at org.apache.wicket.markup.resolver.WicketMessageResolver$MessageContainer.onComponentTagBody(WicketMessageResolver.java:227) ~[wicket-core-8.0.0-M6.jar:8.0.0-M6]
        at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70) ~[wicket-core-8.0.0-M6.jar:8.0.0-M6]
````

**Comment by martin-g** [comment]
After removing all `_pl` I was able to start it on command line and see the error.

**Comment by eximius313** [comment]
1) I believe with IDEA you just have to enable Lombok plugin, but if you want I can remove lombok completly - just say
2) I'm looking into this failure - just give me a second

**Comment by martin-g** [comment]
I've fixed it!
And started in IDEA.
It is just pain.
Please use Wicket Quickstart next time!

**Comment by eximius313** [comment]
ok, sorry

**Comment by martin-g** [comment]
Fixed!
Thank you for reporting it!

**Comment by eximius313** [comment]
Fantastic!  Thank you so much!
Which version can I use?

**Comment by martin-g** [comment]
2.0.0-M5 is released!

**Comment by eximius313** [comment]
I'll check if it fixes https://issues.apache.org/jira/browse/WICKET-6392 - this issue seems related

**Comment by eximius313** [comment]
Ok, I checked it and #676 works perfectly, but WICKET-6392 still doesn't clear the feedback
